sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install pipenv==11.10.0
  - pipenv install --dev
script:
  - pipenv run python setup.py install
  - pipenv run coverage run --source=swagger2case -m unittest discover
after_success:
  - pipenv run coveralls